name: MSYS2 FFmpeg Recipe
runs:
  using: "composite"
  steps:
    - name: Install FFmpeg dependencies
      uses: msys2/setup-msys2@v2
      with:
        msystem: mingw64
        update: true
        install: >-
          git
          base-devel
          unzip
        pacboy:
          binutils:p
          clang:p
          diffutils:p
          libx264:p
          libva:p
          ffnvcodec-headers:p
          nasm:p
          yasm:p
          
    - name: Checkout FFmpeg
      shell: msys2 {0}
      run: |
        git clone https://git.ffmpeg.org/ffmpeg.git ffmpeg
        pushd ffmpeg
        git checkout release/4.4
        git reset --hard aa28df74ab197c49a05fecc40c81e0f8ec4ad0c3
        cp -f ../Media-Transport-Library/ecosystem/ffmpeg_plugin/kahawai_common.c ./libavdevice/
        cp -f ../Media-Transport-Library/ecosystem/ffmpeg_plugin/kahawai_common.h ./libavdevice/
        cp -f ../Media-Transport-Library/ecosystem/ffmpeg_plugin/kahawai_dec.c ./libavdevice/
        cp -f ../Media-Transport-Library/ecosystem/ffmpeg_plugin/kahawai_enc.c ./libavdevice/
        git am --whitespace=fix ../Media-Transport-Library/ecosystem/ffmpeg_plugin/0001-avdevice-kahawai-Add-kahawai-input-output-devices.patch
        
    - name: Fix mingw64 binutils
      shell: msys2 {0}
      run: |
        # Fixes in https://sourceforge.net/p/mingw-w64/mailman/message/29053757/
        cp -f /mingw64/bin/ar.exe /mingw64/bin/x86_64-w64-mingw32-ar.exe
        cp -f /mingw64/bin/dlltool.exe /mingw64/bin/x86_64-w64-mingw32-dlltool.exe
        cp -f /mingw64/bin/nm.exe /mingw64/bin/x86_64-w64-mingw32-nm.exe
        cp -f /mingw64/bin/strip.exe /mingw64/bin/x86_64-w64-mingw32-strip.exe
        cp -f /mingw64/bin/windres.exe /mingw64/bin/x86_64-w64-mingw32-windres.exe         
        
    - name: Setup FFmpeg
      shell: msys2 {0}
      run: >
        ./ffmpeg/configure --arch=x86_64
        --target-os=mingw64
        --prefix=/c/ffmpeg_github2
        --enable-shared
        --enable-nonfree
        --enable-gpl
        --enable-pic
        --disable-lto
        --disable-w32threads
