name: Build Debian Packages
run-name: Build Debian ${{ inputs.package }} Package
on:
  workflow_dispatch:
    inputs:
      package:
        description: 'user space package'
        required: false
        type: string
        default: 'libvirt'
jobs:
  build_package:
    name: Build Package
    runs-on: self-hosted
    steps:
      - id: checkout_libvirt
        name: Checkout libvirt upstream repo
        uses: actions/checkout@v3
        with:
          repository: libvirt/libvirt
          ref: v9.10.0
          submodules: recursive
          path: libvirt
      - id: checkout_frame_deb_builder
        name: Checkout Builder Repo
        uses: actions/checkout@v3
        with:
          repository: intel-sandbox/frameworks.actions.deb-builder
          token: ${{ secrets.DEB_BUILDER_TOKEN }}
          path: deb-builder
      - id: libvirt_deb_builder
        name: Build source package
        uses: ./deb-builder/libvirt/debian/11
        with:
          token: ${{ secrets.DEB_BUILDE_TOKEN }}
      - id: libvirt_build_and_compile
        name: Build & Compile libvirt
        shell: bash
        run: |
          docker run --rm -v $(pwd)/libvirt:/build/libvirt -t registry.gitlab.com/libvirt/libvirt/ci-debian-12:latest meson setup build --error -Dsystem=true -Ddriver_qemu=enabled
