name: Build Debian Packages
run-name: Build ${{ inputs.package }} ${{ inputs.version }} deb Package
on:
  workflow_dispatch:
    inputs:
      package:
        description: 'user space package'
        required: true
        type: string
        default: 'libvirt'
      version:
        description: 'user space version'
        required: true
        type: string
        default: 'v9.10.0'
      distro:
        description: 'distro'
        required: false
        type: string
        default: 'debian'
      distro-ver:
        description: 'Distro Release'
        required: false
        type: choice
        options:
          - '12'
          - '11'
          - '10'
jobs:
  build_package:
    name: Build Package
    runs-on: self-hosted
    strategy:
      fail-fast: true
      matrix:
        distro:
          - ci-${{ inputs.distro }}-${{ inputs.distro-ver }}:latest
          - ci-${{ inputs.distro }}-11:latest
    steps:
      - id: cleanup_libvirt
        name: Cleanout libvirt upstream repo
        run: sudo rm -rf libvirt/ deb-builder/
      - id: checkout_libvirt
        name: Checkout libvirt upstream repo
        uses: actions/checkout@v3
        with:
          repository: libvirt/libvirt
          ref: ${{ inputs.version }}
          submodules: recursive
          path: libvirt
      - id: checkout_frame_deb_builder
        name: Checkout Debian builder repo
        uses: actions/checkout@v3
        with:
          repository: intel-sandbox/frameworks.actions.deb-builder
          token: ${{ secrets.DEB_BUILDER_TOKEN }}
          clean: true
          path: deb-builder
      - id: libvirt_deb_builder
        name: Build source package
        uses: ./deb-builder/libvirt/debian/11
        with:
          token: ${{ secrets.DEB_BUILDER_TOKEN }}
      - id: libvirt_build_and_compile
        name: Build & compile ${{ inputs.package}} on ${{ matrix.distro }}
        shell: bash
        run: |
          echo docker run --rm -v $(pwd)/libvirt:/build/libvirt -v ${{ github.workspace }}/deb-builder:/root --workdir /build/libvirt registry.gitlab.com/libvirt/libvirt/${{ matrix.distro }} git config -l
          docker run --rm -v $(pwd)/libvirt:/build/libvirt -v ${{ github.workspace }}/deb-builder:/root --workdir /build/libvirt registry.gitlab.com/libvirt/libvirt/${{ matrix.distro }} meson setup build --error -Dsystem=true -Ddriver_qemu=enabled
          docker run --rm -v $(pwd)/libvirt:/build/libvirt -v ${{ github.workspace }}/deb-builder:/root --workdir /build/libvirt registry.gitlab.com/libvirt/libvirt/${{ matrix.distro }} ninja -C build
          echo docker run --rm -v $(pwd)/libvirt:/build/libvirt -v ${{ github.workspace }}/deb-builder:/root --workdir /build/libvirt registry.gitlab.com/libvirt/libvirt/${{ matrix.distro }} ninja -C build test
          docker run --rm -v $(pwd)/libvirt:/build/libvirt -v ${{ github.workspace }}/deb-builder:/root --workdir /build/libvirt registry.gitlab.com/libvirt/libvirt/${{ matrix.distro }} sudo ninja -C build install
