name: Open Visual Cloud reusable workflows demo

on:
  push:
    paths: 
      - .github/workflows/msys2_build_reusable.yml
  
jobs:
  call-workflow:
    uses: lab-github/Media-Transport-Library/.github/workflows/msys3_ffmpeg_build.yml@main
    

  
