name: Open Visual Cloud reusable workflows demo

on:
  push:
    paths: 
      - .github/workflows/msys2_build_reusable.yml
defaults:
  run:
    shell: C:/msys64/msys2_shell.cmd -defterm -here -no-start -mingw64 {0}

jobs:
  call-workflow:
      uses: lab-github/Media-Transport-Library/.github/workflows/msys3_ffmpeg_build.yml@main

  
